2018-03-31 11:24:01,040 - api.py[line:40] - WARNING: HTTPConnectionPool(host='restapi.amap.com', port=80): Max retries exceeded with url: /v3/place/text?key=5f2e9ed810bca7a99abc98f3808afce5&keywords=%E7%B1%B3%E4%BA%9A%E5%AE%B6%E5%85%B7&types=&city=140930&citylimit=True&children=1&offset=20&page=1&extensions=all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002272E60BB38>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)), retrying in 0 seconds...
2018-03-31 11:24:19,424 - api.py[line:40] - WARNING: HTTPConnectionPool(host='restapi.amap.com', port=80): Max retries exceeded with url: /v3/place/text?key=5f2e9ed810bca7a99abc98f3808afce5&keywords=%E7%B1%B3%E4%BA%9A%E5%AE%B6%E5%85%B7&types=&city=410923&citylimit=True&children=1&offset=20&page=1&extensions=all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002272E5D7BA8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)), retrying in 0 seconds...
